name: Deploy to Server

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy yt-player app
    runs-on: self-hosted
    
    steps:
      - name: Deploy yt-player
        run: |
          /home/sheldon/scripts/deploy-app.sh yt-player
